### PR TITLE
Fix logging output of graph_nav_util.py

### PR DESCRIPTION
**Pull request by sktometometo**
Fix logging args

### CODE REVIEW

**Review by kaiyu-zheng — APPROVED** [review]
Looks good.

Future refactoring should make the code use f-strings.

**Comment by kaiyu-zheng** [comment]
That sounds good. Could you do this? @sktometometo

**Comment by amessing-bdai** [comment]
@sktometometo Now that the graph_nav modularity PR is in, can you fix the conflicts then we can get this in

**Comment by sktometometo** [comment]
Same change seems already applied.
https://github.com/bdaiinstitute/spot_wrapper/blob/fa4e1772578f521b8d630c7c10612e9366a4cace/spot_wrapper/spot_graph_nav.py#L936

**Pull request closed without merging**
