### PR TITLE
Module for spot check

### PR DESCRIPTION
**Pull request by heuristicus**
Creates the module for spot check interaction.

- [x] This requires working out how to store the robot parameters like `is_sitting`. The previous approach in the modular PR doesn't work because the dictionary is static once initialised.

### CODE REVIEW

**Comment by heuristicus** [comment]
Neither of the ROS drivers have integration for this currently, so I'd say it's low priority for merging.

**Review by jbarry-bdai — APPROVED** [review]
We are not yet using spot check so this can go in without changes to spot ros2.

**Comment by heuristicus** [comment]
@amessing-bdai this is good to merge, I think. We aren't using it anywhere yet.

**Review by amessing-bdai — APPROVED** [review]

**Review by amessing-bdai — APPROVED** [review]

**Review by bhung-bdai — APPROVED** [review]
LGTM

**Pull request merged**
