### PR TITLE
Fix error while there is waypoints without waypoint_ key

### PR DESCRIPTION
**Pull request by sktometometo**
Some graphnav graph contains waypoints whose keys are not "waypoint_*".

Below is my case

```
{'waypoint_0': 'adagio-dog-a.oMMGmFY9cWZADw3I+.pQ==',
 'waypoint_4': 'ashy-drum-uSs6N5vTpZ7de3xpzTtIQw==',
 'Dock 521 Prep Pose': 'banner-bunny-mRdAu0N8Glf01gRwBDrNeA==',
 'waypoint_7': 'beefy-turkey-83J58Jn208bcu9NGQClE9Q==',
 'waypoint_10': 'blurry-rook-Lvxi2A8mKfM.nD6K+gOSBA==',
 'waypoint_13': 'brusk-oxen-npDduGmcao5WcG52bib.tg==',
 'waypoint_6': 'cushy-rabbit-iyoBl8G3DXuRnEu+JCmL8A==',
 'waypoint_20': 'dewy-wombat-dAAj2PFumcS1RCrm.1xfkw==',
 'waypoint_30': 'dyed-gaur-U7vYlULsHpmYX.TUgDmyqw==',
 'waypoint_29': 'each-basset-CXcU8dp3Ca+QIk8.z7U70A==',
 'waypoint_2': 'eased-filly-J5dnsrqRRLRG7G.+p.nKtw==',
 'waypoint_35': 'fetid-bovid-YwaTfGwHOhl8m2Eu9z8o4Q==',
 'Dock 521': 'fizzy-pincer-92.zcSuzaCCSms9kH3gSPg==',
 'waypoint_8': 'flabby-donkey-lx1522ZGloE8jiUPfpBhRw==',
 'waypoint_18': 'fourth-skink-.TbDwo7227KhYdT5hmdZkA==',
 'waypoint_25': 'garbed-fleece-7N5NDZIB5twNaHCTAZmfmQ==',
 'waypoint_5': 'garish-osprey-htvxKeMeHLMr8c+SC4EQdg==',
 'waypoint_17': 'gilled-magpie-8dTPTbOdvs5NgEQhY8mmHA==',
 'waypoint_32': 'hilly-grouse-Qmi1g.P6rQGpaxXwCo7GNg==',
 'waypoint_1': 'known-mink-biCZA3h8jXJMWqIbJNCw6w==',
 'waypoint_11': 'many-mudcat-aLGJsfIs5hcU3eaJM1IGrg==',
 'waypoint_23': 'mazed-drake-1ltHVCA+JLPNp.RfP.Hs1g==',
 'waypoint_19': 'mid-sawfly-+5CQ6c1JUr9uA0CIWuwHzA==',
 'waypoint_3': 'overt-ocelot-BmAQon0IUmgprhZzc+rP9Q==',
 'waypoint_24': 'piano-coyote-B73XVJjJsioJIo2cJQuibQ==',
 'waypoint_28': 'pilary-fish-Cie0xaQj0ZryMZQ1o.KqIQ==',
 'waypoint_15': 'repand-tapir-QU9VE2l2XMSPzE5ha2nzDg==',
 'waypoint_12': 'ruling-wolf-LQw6WlGi+WIOg2yPDXMkww==',
 'waypoint_27': 'smug-cuscus-HBNyYbOX6lW43rI6OkgXgQ==',
 'waypoint_22': 'snubbed-walrus-6mTJbirWGOUJ01tPKXV6bQ==',
 'waypoint_21': 'snuffed-fish-9CJSgY7U23ooAzmHh8akBw==',
 'waypoint_9': 'soiled-avocet-15Kgt2YA0XQic3imRxwfZQ==',
 'waypoint_16': 'sought-bird-2vUiJz6rW6qDfgz.fbirKw==',
 'waypoint_26': 'tetchy-hare-l1+WRfbOWJm4Orq3vY6acg==',
 'waypoint_33': 'unmown-egg-dXbdmIQ5lntGErfaqVA8Pg==',
 'waypoint_31': 'waste-collie-FHwR.Loxe5sUAg4z3CmChQ==',
 'waypoint_14': 'wedged-guinea-ceCZJEfKKb84rMWtl1vBmg=='}
```

This causes error when `list_graph()`

This PR will fix this.

### CODE REVIEW

**Comment by sktometometo** [comment]
Pause this PR until https://github.com/bdaiinstitute/spot_wrapper/pull/44 is merged.

**Comment by sktometometo** [comment]
Rebase on current `origin/main`.

**Comment by heuristicus** [comment]
If I understand correctly, the problem is that the current list of waypoints is expected to be sorted, and the sorting is done based on the expected form `waypoint_N` for the key of each waypoint. If a waypoint name does not conform to this then the listing is broken.

Is there a reason why the waypoint IDs need to be provided in a sorted list? Are waypoints ever accessed in the SDK by the waypoint numbering or is it always based on the ID (`ashy-drum-uSs6N5vTpZ7de3xpzTtIQw==` for example)?

If they don't have to be in order, then we can simplify this function by just returning the values of the dict.

I don't use graphnav components, so some input from people who do would be useful here.

**Comment by sktometometo** [comment]
For my understanding, sorting in list_graph is for convenience to find waypoint ID. When spot creates a graph, key will be the number of the order in which waypoints were created. So if the graph has no branches, starting point is waypoint_0 and end point is waypoint_N-1 and adjacent waypoints are numbered +1 or -1.
If waypoint id list is provided as sorted list, we can easily find initial waypoint, final waypoint and adjacent waypoint s of some waypoints.

**Comment by amessing-bdai** [comment]
@kaiyu-zheng Any extra knowledge to bring to this?

**Pull request closed without merging**
