### PR TITLE
python3.8 workaround and unassigned variable fix

### PR DESCRIPTION
**Pull request by philipsgithub**
- in python 3.8 the typing syntax is not supported
- e was not assigned
- f-strings were not required

### CODE REVIEW

**Comment by philipsgithub** [comment]
note that, by importing 'Tuple' python3.10 is still supported:)

**Comment by heuristicus** [comment]
My preference generally is to import the whole typing module and then use `typing.Tuple` rather than importing individual bits. There's only one place where it's necessary in the dance module but still.

**Comment by heuristicus** [comment]
This needs a black format and then fine to merge.

**Comment by philipsgithub** [comment]
> This needs a black format and then fine to merge.

okay I formatted the code with black, it also changed a `10**9` statement.I hope that's fine:)

**Review by amessing-bdai — APPROVED** [review]

**Review by amessing-bdai — CHANGES_REQUESTED** [review]
Still getting black formatting issues

**Comment by philipsgithub** [comment]
> Still getting black formatting issues

I am sorry, I used black installed via apt instead of pip. so I had v21.12b0-1 instead of v23.3.0 (which black/stable is referring to at the moment)

now it must work \*fingers crossed\*

**Comment by heuristicus** [comment]
This is good to merge now I think.

**Review by amessing-bdai — APPROVED** [review]
Updated for recent changes

**Review by davidwatkins-bdai — APPROVED** [review]

**Pull request merged**
