### PR TITLE
Add aiortc to requirements txt

### PR DESCRIPTION
**Pull request by heuristicus**
Should fix https://github.com/bdaiinstitute/spot_ros2/issues/134.

### CODE REVIEW

**Comment by bhung-bdai** [comment]
I've only ever tested this with 1.5.0. Do you think a generic version works fine enough?

**Review by bhung-bdai — APPROVED** [review]
LGTM. Double checking, I think the versioning is fine but it might be worth making sure.

**Review by bhung-bdai — CHANGES_REQUESTED** [review]
After some deliberation, I've decided to make some edits and edit `spot_ros2` to make the install a bit easier.

**Comment by heuristicus** [comment]
We may need to be careful when specifying versions that the ones we pick are valid for both spot_ros2 and spot_ros, since the latter is running on the older LTS version. In this case I think it's OK.

**Comment by heuristicus** [comment]
Although, should we not be using 3.3.0 for bosdyn now?

**Review by bhung-bdai — APPROVED** [review]
LGTM

**Comment by bhung-bdai** [comment]
@heuristicus I should also add that the SDK versions go together. The file before my changes had a bosdyn-core version of 3.2.3. This should be requiring versions 3.2.3 of the other bosdyn packages.

**Review by amessing-bdai — APPROVED** [review]

**Pull request merged**
